drop table if exists members CASCADE;
create table members
(
    member_id bigint generated by default as identity,
    username varchar(15),
    email varchar(50),
    password varchar(100),
    nickname varchar(12),
    created_date varchar(30),
    modified_date varchar(30),
    primary key (member_id)
)