create table posts
(
    post_id bigint generated by default as identity,
    author_id bigint,
    title tinytext,
    content varchar(5000),
    created_date varchar(30),
    modified_date varchar(30),
    primary key (post_id)
)